# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_director', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelicula', models.IntegerField()),
                ('titulo', models.CharField(max_length=30)),
                ('fecha_publicacion', models.DateTimeField(default=datetime.datetime(2016, 2, 21, 0, 4, 9, 728204, tzinfo=utc))),
                ('anio_estreno', models.IntegerField()),
                ('actores', models.ManyToManyField(to='pelicula.Actor')),
                ('directores', models.ManyToManyField(to='pelicula.Director')),
                ('generos', models.ManyToManyField(to='pelicula.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Usuario'),
        ),
    ]
