# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 21, 0, 30, 56, 97326, tzinfo=utc)),
        ),
    ]
