# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_auto_20160220_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='img', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
