# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0004_auto_20160223_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(upload_to='portada'),
        ),
    ]
