# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0005_auto_20160223_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='actores',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='directores',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='personas',
            field=models.ManyToManyField(to='pelicula.Persona'),
        ),
    ]
