# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0006_auto_20160307_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='id_pelicula',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
    ]
