# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0007_auto_20160307_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='rol',
        ),
        migrations.AddField(
            model_name='persona',
            name='roles',
            field=models.ManyToManyField(to='pelicula.rol'),
        ),
    ]
