# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0012_auto_20160307_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='roles',
            field=models.ManyToManyField(to='pelicula.Rol'),
        ),
    ]
